<?php
$siteUrl = "https://casino.lv";

return [
    'site_url' => $siteUrl,
    'twitter_image_url' => $siteUrl . '/i/logo/logo-500x250.png?v=1.0',
    'twitter_card' => 'summary_large_image',
    'og_image_url' => $siteUrl . '/i/logo/logo-500x250.png?v=1.0',
    'mask_icon' => $siteUrl . '/i/ico/mask-icon.svg?v=1.0',
    'shortcut_favicon' => $siteUrl . '/i/ico/favicon.ico?v=1.0',
    'favicon_mime_type' => 'image/png',
    'favicon_size_16' => $siteUrl . '/i/ico/favicon-16x16.png?v=1.0',
    'favicon_size_32' => $siteUrl . '/i/ico/favicon-32x32.png?v=1.0',
    'favicon_size_96' => $siteUrl . '/i/ico/favicon-96x96.png?v=1.0',
    'favicon_size_192' => $siteUrl . '/i/ico/favicon-192x192.png?v=1.0',
    'apple_touch_icon_size_57' => $siteUrl . '/i/ico/apple-touch-icon-57x57.png?v=1.0',
    'apple_touch_icon_size_60' => $siteUrl . '/i/ico/apple-touch-icon-60x60.png?v=1.0',
    'apple_touch_icon_size_72' => $siteUrl . '/i/ico/apple-touch-icon-72x72.png?v=1.0',
    'apple_touch_icon_size_76' => $siteUrl . '/i/ico/apple-touch-icon-76x76.png?v=1.0',
    'apple_touch_icon_size_114' => $siteUrl . '/i/ico/apple-touch-icon-114x114.png?v=1.0',
    'apple_touch_icon_size_120' => $siteUrl . '/i/ico/apple-touch-icon-120x120.png?v=1.0',
    'apple_touch_icon_size_144' => $siteUrl . '/i/ico/apple-touch-icon-144x144.png?v=1.0',
    'apple_touch_icon_size_152' => $siteUrl . '/i/ico/apple-touch-icon-152x152.png?v=1.0',
    'apple_touch_icon_size_180' => $siteUrl . '/i/ico/apple-touch-icon-180x180.png?v=1.0',
    'android_chrome_manifest_url' => $siteUrl . '/manifest/android_chrome_manifest.json?v=1.0',
    'ms_tile_color' => '#da532c',
    'ms_tile_image' => $siteUrl . '/i/logo/mstile-144x144.png?v=1.0',
    'ms_config_url' => $siteUrl . '/manifest/ms_browserconfig.xml?v=1.0',
    'meta_theme_color' => '#ffffff',
];