version: '3'

networks:
  casino-review-network:
    driver: bridge

services:
  web:
    build: ./web
    depends_on:
      - app
    networks:
      - casino-review-network
    ports:
      - '80:80'
      - 443:443
    restart: unless-stopped

  app:
    build:
      context: ./../..
      dockerfile: ./infra/docker/phpfpm/Dockerfile
      target: ${APP_BUILD_TARGET:-dev-xdebug}
    depends_on:
      db:
        condition: service_healthy
    env_file: ./../../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - casino-review-network
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./../../workspace
        target: /workspace

  db:
    env_file: ./../../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    image: 'postgres:latest'
    networks:
      - casino-review-network
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
        #target: /home/manjaro/coding/my-repo/casino_review/db-data
        # volume:
        #   nocopy: true
      
volumes:
  postgres:
