version: '3'

networks:
  casino-review-network:
    driver: bridge

services:
  web:
    build: ./web
    depends_on:
      - app
    networks:
      - casino-review-network
    ports:
      - '80:80'
      - 443:443

  app:
    build:
      context: ./../..
      dockerfile: ./infra/docker/phpfpm/Dockerfile
      target: ${APP_BUILD_TARGET:-dev-xdebug}
    depends_on:
      - db
    env_file: ./../../.env
    networks:
      - casino-review-network
    restart: always
    volumes:
      - type: bind
        source: ./../../workspace
        target: /workspace

  db:
    env_file: ./../../.env
    image: 'postgres:latest'
    ports:
      # - "${POSTGRES_PORT}:5432" # так работает. но не имеет смысла <host_port>:<container_port>
      - "5432:5432"
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
volumes:
  db-data: