version: '3'

networks:
  casino-review-network:
    driver: bridge

services:
  web:
    build: ./web
    ports:
      - '80:80'
      - 443:443
    depends_on:
      - app
    networks:
      - casino-review-network

  app:
    build: ./phpfpm
    restart: always
    volumes:
      - ./../../workspace:/workspace
    networks:
      - casino-review-network