version: '3'

networks:
  casino-review-network:
    driver: bridge

services:
  web:
    build: ./web
    ports:
      - '80:80'
      - 443:443
    depends_on:
      - app
    networks:
      - casino-review-network

  app:
    build:
      context: ./../..
      dockerfile: ./infra/docker/phpfpm/Dockerfile
      target: ${APP_BUILD_TARGET:-development-xdebug}
    restart: always
    volumes:
      - type: bind
        source: ./../../workspace
        target: /workspace
    networks:
      - casino-review-network