FROM docker-casino-review-base AS deploy

COPY ./infra/docker/phpfpm/php.deploy.ini /usr/local/etc/php/php.ini

COPY ./workspace /workspace

RUN <<EOF
  composer install -q -n --no-ansi --no-dev --no-scripts --no-progress --prefer-dist
  chmod -R 777 storage bootstrap/cache
  php artisan optimize:clear
  php artisan optimize
  apt-get clean
  rm -rf /var/lib/apt/lists/*
EOF

RUN chown -R www-data:www-data /workspace ${COMPOSER_HOME}

USER www-data
