FROM docker-casino-review-base AS dev

COPY ./infra/docker/phpfpm/php.dev.ini /usr/local/etc/php/php.ini

# ------------ development-xdebug --------------

FROM dev AS dev-xdebug

RUN <<EOF
  pecl install xdebug
  docker-php-ext-enable xdebug
EOF

COPY ./infra/docker/phpfpm/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# ----- Notes -----
# COMPOSER_HOME and related actions possibly are not needed and can be removed
#
# For build in deploy mode:
# APP_BUILD_TARGET=deploy make remake
#
# In development mode build and run commands by root, because we need to protect deploy mode only.
